import "./globals.css";

const SITE_URL = "https://demoday.work";
const TITLE = "Demoday — Beautiful clickable product demos";
const DESCRIPTION =
  "Demoday turns any part of your product into an embeddable, clickable walkthrough. Plain HTML, CSS and JS — generated by your coding agent, dropped into your landing page as a single iframe.";

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s · Demoday",
  },
  description: DESCRIPTION,
  keywords: [
    "clickable demo",
    "product demo",
    "interactive demo",
    "iframe demo",
    "landing page demo",
    "Claude Code skill",
    "Claude Code",
    "product walkthrough",
    "SaaS demo",
    "demoday",
  ],
  applicationName: "Demoday",
  authors: [{ name: "Demoday" }],
  creator: "Demoday",
  publisher: "Demoday",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Demoday",
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    creator: "@demoday",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "technology",
};

export const viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Demoday",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Any",
  description: DESCRIPTION,
  url: SITE_URL,
  offers: [
    {
      "@type": "Offer",
      name: "Free",
      price: "0",
      priceCurrency: "USD",
    },
    {
      "@type": "Offer",
      name: "Unbranded",
      price: "20",
      priceCurrency: "USD",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </body>
    </html>
  );
}
